FPS = 1  # Frames per second

SCREEN_WIDTH_PX = 1280
SCREEN_HEIGHT_PX = 720
SCREEN_COLOR = "purple"
SNAKE_COLOR = "black"
SNAKE_WIDTH_PX = 20
SNAKE_HEIGHT_PX = 20
FOOD_COLOR = "green"

KEY_MOVEMENT_PX = 300
